### ISSUE TITLE
Battery mod doesn't work

### ISSUE THREAD

**Issue by maikramer** [InvictrixRom-devices/device_motorola_nash#1]
Sorry, wrong rom

**Comment by me2151** [comment]
So you are reporting an issue using our trees on other ROMS? Why dont you use their trees? these trees are for our ROM specifically.

**Comment by me2151** [comment]
Lol

**Comment by maikramer** [comment]
I feel so sorry, I have too many stared repositories, didn't try your rom yet, but with the problems I'm having with the rom I'm using I will, thanks.
